AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.12
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: Tickets
        DDB_ENDPOINT:
          Fn::If: # use IsLocal condition recommended by LocalStack docs
            - IsLocal # true when sam local/CI wants emulation
            - "http://host.docker.internal:4566" # macOS/Windows Docker Desktop
            - !Ref "AWS::NoValue"
Resources:
  Api:
    Type: AWS::Serverless::HttpApi
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tickets
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  EntryFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: entry_handler.lambda_handler
      CodeUri: ./src
      Events:
        EntryRoute:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: Api
            Path: /entry
            Method: POST
  ExitFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: exit_handler.lambda_handler
      CodeUri: ./src
      Events:
        ExitRoute:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: Api
            Path: /exit
            Method: POST
