[project]
name = "cloud-computing-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.3",
]

[dependency-groups]
dev = [
    "aws-lambda-typing>=2.20.0",
    "boto3-stubs[boto3,essential]>=1.38.3",
]
