version: "3"

tasks:
  hw1:start:
    desc: Start the SAM local API server
    cmds:
      - HW1/create-dynamo-table.sh
      - samlocal local start-api -t HW1/parking-lot.template.yaml --warm-containers EAGER --parameter-overrides EnvironmentName=local
