version: '3'

tasks:
  hw1:start-localstack:
    desc: Start LocalStack container
    cmds:
      - HW1/setup-localstack.sh
  hw1:start:
    desc: Start the SAM local API server
    cmds:
      - HW1/create-dynamo-table.sh
      - samlocal local start-api -t HW1/parking-lot.template.yaml --warm-containers EAGER --parameter-overrides EnvironmentName=local
