version: '3'

tasks:
  hw1:start-localstack:
    desc: Start LocalStack container
    cmds:
      - HW1/setup-localstack.sh
  hw1:start-lambda:
    desc: Start the SAM local API server
    cmds:
      - samlocal local start-api -t HW1/sam-parking-lot.yaml --warm-containers EAGER --parameter-overrides EnvironmentName=local
